#!/bin/ash

commonFunctionsFile=`uci get sensor-restart.sensor.commonFunctionsFile`
networkDeviceBaseFolder=`uci get sensor-restart.sensor.networkDeviceBaseFolder`
interface=`uci get sensor-restart.sensor.interface`
monInterface=`uci get sensor-restart.sensor.monInterface`
curlServer=`uci get sensor-restart.sensor.curlServer`
tmpFileInterfacePresentIter=`uci get sensor-restart.sensor.tmpFileInterfacePresentIter`
tmpFileMonInterfacePresentIter=`uci get sensor-restart.sensor.tmpFileMonInterfacePresentIter`
tmpFileCurlIter=`uci get sensor-restart.sensor.tmpFileCurlIter`
tmpFileMonRx=`uci get sensor-restart.sensor.tmpFileMonRx`
tmpFileMonRxIter=`uci get sensor-restart.sensor.tmpFileMonRxIter`
numOfIterationsInterface=`uci get sensor-restart.sensor.numOfIterationsInterface`
numOfIterationsCurl=`uci get sensor-restart.sensor.numOfIterationsCurl`
numOfIterationsMonInterface=`uci get sensor-restart.sensor.numOfIterationsMonInterface`
numOfIterationsMonRx=`uci get sensor-restart.sensor.numOfIterationsMonRx`
bluInterface=`uci get sensor-restart.sensor.bluInterface`
bluetoothDeviceBaseFolder=`uci get sensor-restart.sensor.bluetoothDeviceBaseFolder`
tmpFileBluInterfacePresentIter=`uci get sensor-restart.sensor.tmpFileBluInterfacePresentIter`
tmpFileBluRx=`uci get sensor-restart.sensor.tmpFileBluRx`
tmpFileBluRxIter=`uci get sensor-restart.sensor.tmpFileBluRxIter`
numOfIterationsBluInterface=`uci get sensor-restart.sensor.numOfIterationsBluInterface`
numOfIterationsBluRx=`uci get sensor-restart.sensor.numOfIterationsBluRx`

. "$commonFunctionsFile"

#input: no input
#output: cleaning up local files.
cleanup() {
	
	setValueInFile "0" "$tmpFileInterfacePresentIter"
	setValueInFile "0" "$tmpFileMonInterfacePresentIter"
	setValueInFile "0" "$tmpFileMonRxIter"
	setValueInFile "0" "$tmpFileBluInterfacePresentIter"
	setValueInFile "0" "$tmpFileBluRxIter"
	deleteDirectoryOrFile "$tmpFileInterfacePresentIter"
	deleteDirectoryOrFile "$tmpFileMonInterfacePresentIter"
	deleteDirectoryOrFile "$tmpFileMonRx"
	deleteDirectoryOrFile "$tmpFileMonRxIter"
	deleteDirectoryOrFile "$tmpFileBluInterfacePresentIter"
	deleteDirectoryOrFile "$tmpFileBluRx"
	deleteDirectoryOrFile "$tmpFileBluRxIter"
}

#input: message to be printed with reboot
#output: message printed on console
restartSensor() {
	printInfo "Prepare to reboot: $1"
	cleanup
	sync
	printInfo "rebooting"
	# if machine hangs, it will restart because of watchdog, otherwise because of reboot command below.
	reboot
	exit
}

#input: value, file.
#output: file set with that iteration value.
setValueInFile() {
	printInfo "set value: $1 in file: $2"
	echo $1 > $2
}

#input: iteration file name
#output: iteration incremented in the file.
incrementIteration() {
	checkIfFileExists $1	
	if [ "$?" -eq "1" ];
	then
		setValueInFile "0" "$1"
	else
		printInfo "file: $1 exists"
		printInfo "increment iteration in file: $1"
       		iteration=`getValueFromFile $1`
	        printInfo "currIteration: $iteration"
       		iteration=$((iteration+1))
	        printInfo "newIteration: $iteration"
		setValueInFile $iteration "$1"
	fi
}

#Input: fileName
#Output: Value in the file
getValueFromFile() {
	echo `cat $1`
}

#input: iteration threshold, file name, restart message
#output: no output, restarts sensor.
restartIfIterationExceeded() {

	printInfo "check if Iterations greater than $1 in file: $2"
        iteration=`getValueFromFile $2`
        printInfo "iteration: $iteration"
        if [ $iteration -gt $1 ];
        then
        	restartSensor "iteration: $iteration greater than numOfIterations: $1 in file: $2"
        fi

}

#input: interface, iteration file name
#output: no output, resets iteration.
resetIfInterfacePresent() {
	checkIfInterfacePresent $1 $2
	if [ $? -eq 0 ];
	then
        	setValueInFile "0" "$3"
	fi
}

#input: iteration file name
#output: no output, resets iteration.
resetIfPinging() {
        checkIfPingWorks $pingServer
        if [ $? -eq 0 ];
        then
                setValueInFile "0" "$1"

        fi
}


#input: iteration file name
#output: no output, resets iteration.
resetIfCurling() {
        checkIfCurlWorks $curlServer
        if [ $? -eq 0 ];
        then
                setValueInFile "0" "$1"

        fi
}

#Input: interface name
#output: Rx Bytes
getRxBytesWifi(){
	echo `/sbin/ifconfig $1 | grep 'RX bytes' | awk -F":" '{print $2}'| awk -F" " '{print $1}'`
}

#input: interface name, rx bytes file name, iteration file name
#output: no output, iteration reset in file
resetIterationIfActivityWifi() {

checkIfFileExists $2
if [ "$?" -eq "1" ];
then
        printInfo "$2 not present. create new file and save present monrx"
        monRx=`getRxBytesWifi $1`
        printInfo "monRx: $monRx"
        setValueInFile "$monRx" "$2"
	setValueInFile "0" "$3"
else
        printInfo "getting previous rx from $2"
        prevMonRx=`getValueFromFile $2`
        printInfo "prevMonRx: $prevMonRx"
        printInfo "getting currMonRx"
        currMonRx=`getRxBytesWifi $1`
        printInfo "currMonRx: $currMonRx"
        setValueInFile "$currMonRx" "$2"
        printInfo "check if currMonRx greater than prevMonRx for interface: $1"
        if [ $currMonRx -gt $prevMonRx ];
        then
                printInfo "currMonRx: $currMonRx is greater than prevMonRx: $prevMonRx"
	        setValueInFile "0" "$3"
	fi
fi

}

#Input: interface name
#output: Rx Bytes
getRxBytesBluetooth(){
	echo `hciconfig $1 | grep 'RX bytes' | awk -F":" '{print $2}'| awk -F" " '{print $1}'`
}

#input: interface name, rx bytes file name, iteration file name
#output: no output, iteration reset in file
resetIterationIfActivityBluetooth() {

checkIfFileExists $2
if [ "$?" -eq "1" ];
then
        printInfo "$2 not present. create new file and save present blurx"
        bluRx=`getRxBytesBluetooth $1`
        printInfo "bluRx: $bluRx"
        setValueInFile "$bluRx" "$2"
	setValueInFile "0" "$3"
else
        printInfo "getting previous rx from $2"
        prevBluRx=`getValueFromFile $2`
        printInfo "prevBluRx: $prevBluRx"
        printInfo "getting currBluRx"
        currBluRx=`getRxBytesBluetooth $1`
        printInfo "currBluRx: $currBluRx"
        setValueInFile "$currBluRx" "$2"
        printInfo "check if currBluRx greater than prevBluRx for interface: $1"
        if [ $currBluRx -gt $prevBluRx ];
        then
                printInfo "currBluRx: $currBluRx is greater than prevBluRx: $prevBluRx"
	        setValueInFile "0" "$3"
	fi
fi

}

incrementIteration "$tmpFileInterfacePresentIter"
incrementIteration "$tmpFileMonInterfacePresentIter"
incrementIteration "$tmpFileCurlIter"


restartIfIterationExceeded "$numOfIterationsCurl" "$tmpFileCurlIter"
resetIfCurling "$tmpFileCurlIter"

restartIfIterationExceeded "$numOfIterationsInterface" "$tmpFileInterfacePresentIter"
resetIfInterfacePresent "$interface" "$networkDeviceBaseFolder" "$tmpFileInterfacePresentIter"

restartIfIterationExceeded "$numOfIterationsMonInterface" "$tmpFileMonInterfacePresentIter"
resetIfInterfacePresent "$monInterface" "$networkDeviceBaseFolder" "$tmpFileMonInterfacePresentIter"

restartIfIterationExceeded "$numOfIterationsBluInterface" "$tmpFileBluInterfacePresentIter"
resetIfInterfacePresent "$bluInterface" "$bluetoothDeviceBaseFolder" "$tmpFileBluInterfacePresentIter"

checkIfInterfacePresent $monInterface
if [ $? -eq 0 ];
then
	incrementIteration "$tmpFileMonRxIter"
	restartIfIterationExceeded "$numOfIterationsMonRx" "$tmpFileMonRxIter"
	resetIterationIfActivityWifi "$monInterface" "$tmpFileMonRx" "$tmpFileMonRxIter"
fi

checkIfInterfacePresent $bluInterface
if [ $? -eq 0 ];
then
	incrementIteration "$tmpFileBluRxIter"
	restartIfIterationExceeded "$numOfIterationsBluRx" "$tmpFileBluRxIter"
	resetIterationIfActivityBluetooth "$bluInterface" "$tmpFileBluRx" "$tmpFileBluRxIter"
fi

printInfo "not restarting"
sync


