#!/bin/sh
echo "Content-type: text/html"
echo 

echo '<html><head><title>Radiolocus</title><link href="../styles/style.css" rel="stylesheet" type="text/css"><link rel="icon" href="../images/favicon.ico" type="x-icon"></head>'


echo '<body><div id="body"><div class="margin"><a href="http://radiolocus.com" target="http://radiolocus.com"><img src="../images/logo.png" class="logo"></a><ul class="header"><li><a href="./overview">Status</a></li><li><a href="./sensor_config">Sensor</a></li><li><a href="./wifi_config">Wi-Fi</a></li><li><a href="./3g_config">3G Dongle</a></li><li><a href="./ethernet_config">Ethernet</a></li> <li><a href="./proxy_config">Proxy</a></li><<li><a href="../contact.html">Contact</a></li></ul>'

  echo "<div id="header_form">Configure 3G Dongle</div><div class="form"><form method=GET action=\"./3g_process\">"\
       '<table nowrap="" class="table"><tbody>'\
          '<tr><td>RNDIS</td><td><input type="checkbox" id="is_rndis" name="is_rndis" onchange="rndisVerify();" value="rndis"</td></tr>'\
          '<tr><td>APN</TD><TD><input type="text" id="apn" name="val_apn" size=12></td></tr>'\
          '<tr><td>PINCODE</TD><TD><input type="text" id="pincode" name="val_pincode" size=12></td></tr>'\
          '<tr><td>SERVICE</td><td><input type="text" id="service" name="val_service" size=12 value=""></td></tr>'\
          '<tr><td>DEVICE</td><td><input type="text" id="device" name="val_device" size=12 value=""></td></tr>'\
          '<tr><td>USERNAME</td><td><input type="text" id="username" name="val_username" size=12 value=""></td></tr>'\
          '<tr><td>PASSWORD</td><td><input type="text" id="password" name="val_password" size=12 value=""></td>'\
          '<tr><td>MAX-WAIT</td><td><input type="text" id="maxwait" name="val_maxwait" size=12 value=""></td>'\
          '<tr><td>DEFAUT-ROUTE</td><td><input type="text" id="defroute" name="val_defroute" size=12 value=""></td>'\
          '</tr></tbody></table>'

  echo '<br/><br><div id="submit"><input type="submit" value="Save">'\
       '<input type="reset" value="Reset"></div></form></div>'

   echo '<script>function rndisVerify() {'\
        'var dd = document.getElementById("is_rndis").checked;'\
        'if (dd == false){'\
        'document.getElementById("apn").disabled=false;'\
        'document.getElementById("pincode").disabled=false;'\
        'document.getElementById("service").disabled=false;'\
        'document.getElementById("device").disabled=false;'\
        'document.getElementById("username").disabled=false;'\
        'document.getElementById("password").disabled=false;'\
        'document.getElementById("maxwait").disabled=false;'\
        'document.getElementById("defroute").disabled=false;'\
        '}else{'\
        'document.getElementById("apn").disabled=true;'\
        'document.getElementById("pincode").disabled=true;'\
        'document.getElementById("service").disabled=true;'\
        'document.getElementById("device").disabled=true;'\
        'document.getElementById("username").disabled=true;'\
        'document.getElementById("password").disabled=true;'\
        'document.getElementById("maxwait").disabled=true;'\
        'document.getElementById("defroute").disabled=true;'\
        '}'\
        '}'\
        '</script>'

echo '<br/><div><div class="footer" ><span>&#169; 2017 Radiolocus. All rights reserved.</span><div/></div></div></div></body>'

echo '</html>'


